# Prometheus Configuration for RCM Application - Production

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    environment: 'production'
    service: 'rcm'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s

  # RCM Application
  - job_name: 'rcm-app'
    static_configs:
      - targets: ['rcm-app:3000']
    metrics_path: '/api/v1/monitoring/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MySQL Database
  - job_name: 'mysql'
    static_configs:
      - targets: ['rcm-db-prod:3306']
    scrape_interval: 60s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['rcm-redis-prod:6379']
    scrape_interval: 60s

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['rcm-nginx-prod:80']
    metrics_path: '/nginx_status'
    scrape_interval: 60s

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 60s